name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu22.04

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ ! -d "/var/www/html/cicd" ]; then
              mkdir -p /var/www/html/cicd
            fi

            if [ ! -d "/var/www/html/cicd/2305093" ]; then
              mkdir -p /var/www/html/cicd/2305093
            fi

            cd /var/www/html/cicd/

            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi

            chmod -R 755 /var/www/html/cicd
